import { IStaticUsers } from '@/store/types';

export const data: IStaticUsers[] = [
    {
        id: 1,
        name: 'Anatoly',
        fullName: 'Anatoly Dervishi',
        email: 'anatoly@gmail.com',
        age: 30,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 2,
        name: 'Anna',
        fullName: 'Anna Anatoly',
        email: 'anna@gmail.com',
        age: 25,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 3,
        name: 'Hugo',
        fullName: 'Hugo Begu',
        email: 'hugo@gmail.com',
        age: 32,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 4,
        name: 'Daniel',
        fullName: 'Daniel Hasani',
        email: 'daniel@gmail.com',
        age: 22,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 5,
        name: 'Emma',
        fullName: 'Emma Shkodra',
        email: 'emma@gmail.com',
        age: 20,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 6,
        name: 'Gabriel',
        fullName: 'Gabriel Steiner',
        email: 'gabriel@gmail.com',
        age: 27,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 7,
        name: 'John',
        fullName: 'John Hofer',
        email: 'john@gmail.com',
        age: 18,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 8,
        name: 'Diego',
        fullName: 'Diego Hofer',
        email: 'diego@gmail.com',
        age: 24,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 9,
        name: 'Leonardo',
        fullName: 'Leonardo Hofer',
        email: 'leonardo@gmail.com',
        age: 40,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 10,
        name: 'George',
        fullName: 'George Hofer',
        email: 'george@gmail.com',
        age: 45,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 11,
        name: 'Mia',
        fullName: 'Mia Hofer',
        email: 'mia@gmail.com',
        age: 27,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 12,
        name: 'Anatoly',
        fullName: 'Anatoly Hofer',
        email: 'anatoly@gmail.com',
        age: 30,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 13,
        name: 'Anna',
        fullName: 'Anna Hofer',
        email: 'anna@gmail.com',
        age: 25,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 14,
        name: 'Hugo',
        fullName: 'Hugo Hofer',
        email: 'hugo@gmail.com',
        age: 32,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 15,
        name: 'Daniel',
        fullName: 'Daniel Hofer',
        email: 'daniel@gmail.com',
        age: 22,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 16,
        name: 'Emma',
        fullName: 'Emma Hofer',
        email: 'emma@gmail.com',
        age: 20,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 17,
        name: 'Gabriel',
        fullName: 'Gabriel Hofer',
        email: 'gabriel@gmail.com',
        age: 27,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 18,
        name: 'John',
        fullName: 'John Hofer',
        email: 'john@gmail.com',
        age: 18,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 19,
        name: 'Diego',
        fullName: 'Diego Hofer',
        email: 'diego@gmail.com',
        age: 24,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 20,
        name: 'Leonardo',
        fullName: 'Leonardo Hofer',
        email: 'leonardo@gmail.com',
        age: 40,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 21,
        name: 'George',
        fullName: 'George Hofer',
        email: 'george@gmail.com',
        age: 45,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 22,
        name: 'Mia',
        fullName: 'Mia Hofer',
        email: 'mia@gmail.com',
        age: 27,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 23,
        name: 'George',
        fullName: 'George Hofer',
        email: 'george@gmail.com',
        age: 45,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 24,
        name: 'Mia',
        fullName: 'Mia Hofer',
        email: 'mia@gmail.com',
        age: 27,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 25,
        name: 'Anatoly',
        fullName: 'Anatoly Hofer',
        email: 'anatoly@gmail.com',
        age: 30,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 26,
        name: 'Anna',
        fullName: 'Anna Hofer',
        email: 'anna@gmail.com',
        age: 25,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 27,
        name: 'Hugo',
        fullName: 'Hugo Hofer',
        email: 'hugo@gmail.com',
        age: 32,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 28,
        name: 'Daniel',
        fullName: 'Daniel Hofer',
        email: 'daniel@gmail.com',
        age: 22,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 29,
        name: 'Emma',
        fullName: 'Daniel Hofer',
        email: 'emma@gmail.com',
        age: 20,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
    {
        id: 30,
        name: 'Anatoly',
        fullName: 'Anatoly Hofer',
        email: 'anatoly@gmail.com',
        age: 30,
        actions: 'some actions...',
        address: '1600 Amphitheatre Parkway Mountain View',
        image: 'https://cdn.pixabay.com/photo/2020/07/01/12/58/icon-5359553_1280.png',
    },
];
